### ISSUE TITLE
Problema con los enlaces internos y externos en la nueva versión de JW Library

### ISSUE THREAD

**Issue by yuniermv** [MisaelArciniega/JWPUB#1]
Excelente trabajo con el libro de hace años, `comentario sobre la carta de Santiago`. No obstante, en el índice, los enlaces internos **no funcionan**. Y la razón es que la nueva versión de JW Library por lo menos en _Android_ debe usar los `MEPS ID` correctos.
@livrasand @MisaelArciniega

**Comment by MisaelArciniega** [comment]
Revisé en mi dispositivo y efectivamente hay error y no lo había notado. 
Lo revisaré y habrá actualización del archivo.
Gracias @yuniermv

**Comment by yuniermv** [comment]
Muy bien hermano. Si puedes me dices cómo solucionar el problema de los
MEPS ID. También creo mis JWPUB personales.

**Comment by MisaelArciniega** [comment]
Realmente es un problema en la tabla Extract y DocumentExtract por que las preguntas las puse como referencias externas, pero no se preocupe lo repararé.
Por cierto, podría ver cuales ha creado?

**Comment by yuniermv** [comment]
Escríbeme a mi WhatsApp. +5359460735

**Comment by yuniermv** [comment]
Aunque creo que por lo menos en el índice (TOC) Table of contents, son
enlaces type "it" internos. Al ser un enlace interno, no consulta la tabla
Extract
